version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    target-branch: "develop"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      npm-deps:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/backend"
    target-branch: "develop"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      python-deps:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      actions-deps:
        patterns:
          - "*"
