name: Запрос возможности
description: Предложение идеи или улучшения.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую проблему это решает?
      description: Опишите проблему, а не предлагаемое решение.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Как должно быть?
    validations:
      required: false
